### ISSUE TITLE
_

### ISSUE THREAD

**Issue by ajmtrz** [UBERMALLOW/frameworks_base#1]

**Comment by Cl3Kener** [comment]
It's just a revert of DayNight mode. https://github.com/UBERMALLOW/frameworks_base/commit/8566d94617d4f94412d25f2f742a6090e32f5cc9 I don't consider these errors and don't plan on fixing them. If that bothers you this is clearly not the ROM for you and you should find another ROM and/or start your own.

**Comment by discipuloosho** [comment]
Thanks for reponse. I haven't modified anything from source.

**Comment by discipuloosho** [comment]
Thanks for reponse. I haven't modified anything from source.
Following my commands:
repo init -u https://github.com/UBERMALLOW/manifest.git -b stock && repo sync && source build/envsetup.sh && lunch uberstock_shamu-user && make -j4
Anything adds or modifications.
No need to be rude.
